### ISSUE TITLE
Docs.gauge.org - issues while loading the website

### ISSUE THREAD

**Issue by nyuday** [getgauge/docs.gauge.org#113]
Google shows that docs website throws some issues on loading - https://search.google.com/test/mobile-friendly?id=TibskRzznnUw-2yo2lG3qQ 

This impacts SEO - overall, the site is mobile friendly but we need to get rid of the page load issues.

**Comment by NivedhaSenthil** [comment]
Fixed resource couldn't be loaded issues with asserts that we were loading from preview.gauge.org, and the console errors are fixed already when sphinx was upgraded. There are few external dependencies that restricts bots using robot.txt which we do not have control on. Fixes available on master https://search.google.com/test/mobile-friendly?id=RVIFue1WGvbst6rfOQAiTA

**Comment by nehashri** [comment]
Still able to see few console log errors 
<img width="723" alt="Screenshot 2019-04-01 at 12 06 06 PM" src="https://user-images.githubusercontent.com/5715387/55307916-9b4e8800-5476-11e9-8181-bce4d5201edc.png">

**Comment by Apoorva-GA** [comment]
- The one error with site.js file I have added `use strict` to the site.js file and build the `gauge.org` and rebuild the `docs_gauge_org`, but I still see the error.
- The Unexpected token ) in theme.js I don’t see any issue there.

Also I don’t see these console errors when I hit https://docs.gauge.org/master/index.html from my browser
